language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before install
  - composer self-update

install:
  - composer install --dev

script: 
  - phpunit -c phpunit.xml.dist

notifications:
  email:
    - info@endroid.nl
